version: 0.1

phases:
  install:
    commands:
      - echo installing nodejs...
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
      - . ~/.nvm/nvm.sh
      - nvm install node
      # - yum install -y nodejs  #Amazon Linux based AMI uses the yum command instead of apt-get
  pre_build:
    commands:
      - echo installing dependencies...
      - npm i -g @angular/cli
      - npm install
  build:
    commands:
      # - echo testing...
      # - echo building...
      - ng build --prod
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist/my-dream-app